#!/bin/bash
# QUICK START GUIDE - Copy and paste these commands

echo "============================================"
echo "QUANTUM ML TRAINING - QUICK START"
echo "============================================"
echo ""
echo "Step 1: Log into Scholar"
echo "  ssh yournetid@scholar.rcac.purdue.edu"
echo ""
echo "Step 2: Navigate to project directory"
echo "  cd /path/to/quantum_xray"
echo ""
echo "Step 3: Setup environment (FIRST TIME ONLY)"
echo "  chmod +x setup_env.sh"
echo "  ./setup_env.sh"
echo ""
echo "Step 4: Configure your data"
echo "  nano preprocess.py"
echo "  # Change DATA_ROOT = '/path/to/your/data'"
echo ""
echo "Step 5: Update email in submit script"
echo "  nano submit_job.sh"
echo "  # Change #SBATCH --mail-user=your_email@purdue.edu"
echo ""
echo "Step 6: Create logs directory"
echo "  mkdir -p logs"
echo ""
echo "Step 7: Test interactively (OPTIONAL but RECOMMENDED)"
echo "  srun -A scholar --partition=gpu --gres=gpu:1 --time=00:30:00 --pty bash"
echo "  module load anaconda"
echo "  source activate quantum_ml"
echo "  python preprocess.py  # Test data"
echo "  # Edit train.py: set n_epochs=2 for quick test"
echo "  python train.py  # Test training"
echo "  exit  # Exit interactive session"
echo ""
echo "Step 8: Submit full training job"
echo "  sbatch submit_job.sh"
echo ""
echo "Step 9: Monitor job"
echo "  squeue -u \$USER  # Check status"
echo "  tail -f logs/quantum_*.out  # Watch output"
echo ""
echo "Step 10: Get results when done"
echo "  ls outputs/  # View saved files"
echo ""
echo "============================================"
echo "COMMON COMMANDS"
echo "============================================"
echo ""
echo "Check your jobs:"
echo "  squeue -u \$USER"
echo ""
echo "Cancel a job:"
echo "  scancel <job_id>"
echo ""
echo "Check cluster status:"
echo "  sinfo -p gpu"
echo ""
echo "View job details:"
echo "  scontrol show job <job_id>"
echo ""
echo "Check account usage:"
echo "  mybalance"
echo ""
echo "============================================"
echo "TROUBLESHOOTING"
echo "============================================"
echo ""
echo "Out of Memory? Reduce batch size in train.py:"
echo "  batch_size = 32  # or 16"
echo ""
echo "Job too slow? Check GPU utilization:"
echo "  nvidia-smi  # Run in interactive session"
echo ""
echo "Module not found? Check available:"
echo "  module avail"
echo ""
echo "Data not loading? Verify path:"
echo "  python preprocess.py"
echo ""
echo "============================================"
